import type {
  CollectionEvaluation,
  ProjectUpgradeCampaign,
  ScoringModelVersion,
  WalletBehaviorMetrics,
  WalletPortfolioSummary,
  ScoreCategoryKey,
} from "@/lib/types";

const categoryWeights: Record<ScoreCategoryKey, number> = {
  market_health: 25,
  liquidity: 15,
  community_strength: 15,
  builder_team: 15,
  product_utility: 10,
  culture_art_brand: 10,
  holder_value_rewards: 5,
  skin_in_the_game: 5,
};

export const DEFAULT_SCORING_VERSION: ScoringModelVersion = {
  id: "version_v1_market_heavy",
  modelId: "nftscore_core",
  modelName: "NFTScore Core",
  versionName: "v1 Market Heavy",
  isActive: true,
  description:
    "Balances market/liquidity with builder, community, and utility signals.",
  createdAt: new Date().toISOString(),
  categoryWeights,
  factorRules: [
    {
      key: "floor_price_stability",
      label: "Floor Price Stability",
      category: "market_health",
      enabled: true,
      weight: 0.22,
      sourceMetric: "floorChange24hPct",
      normalization: "inverse_min_max",
      minValue: -40,
      maxValue: 40,
    },
    {
      key: "volume_7d",
      label: "Volume (7d)",
      category: "market_health",
      enabled: true,
      weight: 0.21,
      sourceMetric: "volume7dEth",
      normalization: "min_max",
      minValue: 50,
      maxValue: 30000,
    },
    {
      key: "holder_count",
      label: "Holder Count",
      category: "market_health",
      enabled: true,
      weight: 0.2,
      sourceMetric: "holderCount",
      normalization: "min_max",
      minValue: 100,
      maxValue: 25000,
    },
    {
      key: "unique_owners",
      label: "Unique Owner %",
      category: "market_health",
      enabled: true,
      weight: 0.18,
      sourceMetric: "uniqueOwnerPct",
      normalization: "min_max",
      minValue: 10,
      maxValue: 80,
    },
    {
      key: "sales_count_24h",
      label: "Sales Count (24h)",
      category: "market_health",
      enabled: true,
      weight: 0.19,
      sourceMetric: "sales24h",
      normalization: "min_max",
      minValue: 2,
      maxValue: 1200,
    },
    {
      key: "listed_supply_ratio",
      label: "Listed Supply %",
      category: "liquidity",
      enabled: true,
      weight: 0.28,
      sourceMetric: "listedPct",
      normalization: "inverse_min_max",
      minValue: 1,
      maxValue: 50,
    },
    {
      key: "top_offer_strength",
      label: "Top Offer Strength",
      category: "liquidity",
      enabled: true,
      weight: 0.35,
      sourceMetric: "topOfferEth",
      normalization: "min_max",
      minValue: 0.05,
      maxValue: 30,
    },
    {
      key: "bid_depth",
      label: "Bid Depth",
      category: "liquidity",
      enabled: true,
      weight: 0.37,
      sourceMetric: "bidDepthEth",
      normalization: "min_max",
      minValue: 0.3,
      maxValue: 250,
    },
    {
      key: "longevity_years",
      label: "Length of Operation",
      category: "builder_team",
      enabled: true,
      weight: 0.3,
      sourceMetric: "yearsActive",
      normalization: "min_max",
      minValue: 0.5,
      maxValue: 10,
    },
    {
      key: "real_business_revenue",
      label: "Real Business Revenue",
      category: "product_utility",
      enabled: true,
      weight: 0.4,
      sourceMetric: "hasBusinessRevenue",
      normalization: "boolean",
    },
    {
      key: "token_utility",
      label: "Token Utility",
      category: "product_utility",
      enabled: true,
      weight: 0.25,
      sourceMetric: "hasToken",
      normalization: "boolean",
    },
    {
      key: "reward_program",
      label: "Reward Platform",
      category: "holder_value_rewards",
      enabled: true,
      weight: 0.55,
      sourceMetric: "hasRewardPlatform",
      normalization: "boolean",
    },
    {
      key: "irl_events",
      label: "IRL Experiences",
      category: "holder_value_rewards",
      enabled: true,
      weight: 0.45,
      sourceMetric: "hasIrlEvents",
      normalization: "boolean",
    },
    {
      key: "social_x_presence",
      label: "X Activity Baseline",
      category: "community_strength",
      enabled: true,
      weight: 0.4,
      sourceMetric: "xUrl",
      normalization: "boolean",
    },
    {
      key: "social_discord_presence",
      label: "Discord Activity Baseline",
      category: "community_strength",
      enabled: true,
      weight: 0.35,
      sourceMetric: "discordUrl",
      normalization: "boolean",
    },
    {
      key: "holder_uniqueness",
      label: "Holder Distribution Quality",
      category: "community_strength",
      enabled: true,
      weight: 0.25,
      sourceMetric: "uniqueOwnerPct",
      normalization: "min_max",
      minValue: 10,
      maxValue: 80,
    },
    {
      key: "founder_presence",
      label: "Founder Profile Completeness",
      category: "builder_team",
      enabled: true,
      weight: 0.35,
      sourceMetric: "founderNames",
      normalization: "boolean",
    },
    {
      key: "dev_founder",
      label: "Dev Founder Present",
      category: "builder_team",
      enabled: true,
      weight: 0.35,
      sourceMetric: "hasDevFounder",
      normalization: "boolean",
    },
    {
      key: "brand_quality_proxy",
      label: "Brand / Art Strength Proxy",
      category: "culture_art_brand",
      enabled: true,
      weight: 0.5,
      sourceMetric: "verified",
      normalization: "boolean",
    },
    {
      key: "culture_persistence_proxy",
      label: "Culture Persistence Proxy",
      category: "culture_art_brand",
      enabled: true,
      weight: 0.5,
      sourceMetric: "yearsActive",
      normalization: "min_max",
      minValue: 0.5,
      maxValue: 8,
    },
    {
      key: "community_funding_signal",
      label: "Community Contributor Signal",
      category: "skin_in_the_game",
      enabled: true,
      weight: 0.5,
      sourceMetric: "claimed",
      normalization: "boolean",
    },
    {
      key: "profile_completeness_signal",
      label: "Profile Completeness",
      category: "skin_in_the_game",
      enabled: true,
      weight: 0.5,
      sourceMetric: "officialWebsite",
      normalization: "boolean",
    },
  ],
};

export const MOCK_SCORING_VERSIONS: ScoringModelVersion[] = [
  DEFAULT_SCORING_VERSION,
  {
    ...DEFAULT_SCORING_VERSION,
    id: "version_v2_revenue_focused",
    versionName: "v2 Revenue Focused",
    categoryWeights: {
      ...categoryWeights,
      market_health: 18,
      product_utility: 18,
      builder_team: 17,
      liquidity: 12,
      community_strength: 12,
      culture_art_brand: 10,
      holder_value_rewards: 8,
      skin_in_the_game: 5,
    },
  },
  {
    ...DEFAULT_SCORING_VERSION,
    id: "version_v3_collector_culture",
    versionName: "v3 Collector Culture",
    categoryWeights: {
      ...categoryWeights,
      market_health: 18,
      liquidity: 12,
      community_strength: 18,
      builder_team: 14,
      product_utility: 10,
      culture_art_brand: 15,
      holder_value_rewards: 8,
      skin_in_the_game: 5,
    },
  },
];

export const MOCK_COLLECTIONS: CollectionEvaluation[] = [
  {
    profile: {
      slug: "azuki",
      name: "Azuki",
      imageUrl: "https://i.seadn.io/gae/example-azuki.png",
      bannerUrl: "https://i.seadn.io/gae/example-azuki-banner.png",
      description: "Anime-native brand building metaverse storytelling.",
      chain: "ethereum",
      openseaUrl: "https://opensea.io/collection/azuki",
      officialWebsite: "https://www.azuki.com",
      xUrl: "https://x.com/azuki",
      discordUrl: "https://discord.gg/azuki",
      foundedAt: "2022-01-12T00:00:00.000Z",
      founderNames: ["Zagabond"],
      verified: true,
      claimed: true,
      hasToken: false,
      hasRewardPlatform: true,
      hasIrlEvents: true,
      hasBusinessRevenue: true,
      hasDevFounder: true,
      dataConfidenceLevel: "full_evaluation",
    },
    marketSnapshot: {
      collectionSlug: "azuki",
      floorPriceEth: 5.92,
      floorChange24hPct: 3.4,
      volume24hEth: 780,
      volume7dEth: 3420,
      sales24h: 164,
      holderCount: 4900,
      uniqueOwnerPct: 53.5,
      listedCount: 334,
      listedPct: 3.34,
      topOfferEth: 5.42,
      bidDepthEth: 112.6,
      whaleConcentrationPct: 18.4,
      capturedAt: new Date().toISOString(),
    },
    score: {
      modelId: "nftscore_core",
      versionId: "version_v1_market_heavy",
      overallScore: 83,
      confidenceScore: 88,
      computedAt: new Date().toISOString(),
      categories: [],
      explainability: [],
    },
  },
  {
    profile: {
      slug: "pudgypenguins",
      name: "Pudgy Penguins",
      imageUrl: "https://i.seadn.io/gae/example-pudgy.png",
      bannerUrl: "https://i.seadn.io/gae/example-pudgy-banner.png",
      description: "Consumer-friendly NFT brand with strong culture.",
      chain: "ethereum",
      openseaUrl: "https://opensea.io/collection/pudgypenguins",
      officialWebsite: "https://www.pudgypenguins.com",
      xUrl: "https://x.com/pudgypenguins",
      discordUrl: "https://discord.gg/pudgypenguins",
      foundedAt: "2021-07-23T00:00:00.000Z",
      founderNames: ["Luca Netz"],
      verified: true,
      claimed: true,
      hasToken: true,
      hasRewardPlatform: true,
      hasIrlEvents: true,
      hasBusinessRevenue: true,
      hasDevFounder: false,
      dataConfidenceLevel: "verified",
    },
    marketSnapshot: {
      collectionSlug: "pudgypenguins",
      floorPriceEth: 9.1,
      floorChange24hPct: -2.1,
      volume24hEth: 1240,
      volume7dEth: 6400,
      sales24h: 210,
      holderCount: 5231,
      uniqueOwnerPct: 56.1,
      listedCount: 280,
      listedPct: 3.15,
      topOfferEth: 8.7,
      bidDepthEth: 199.4,
      whaleConcentrationPct: 21.3,
      capturedAt: new Date().toISOString(),
    },
    score: {
      modelId: "nftscore_core",
      versionId: "version_v1_market_heavy",
      overallScore: 86,
      confidenceScore: 82,
      computedAt: new Date().toISOString(),
      categories: [],
      explainability: [],
    },
  },
  {
    profile: {
      slug: "doodles-official",
      name: "Doodles",
      imageUrl: "https://i.seadn.io/gae/example-doodles.png",
      bannerUrl: "https://i.seadn.io/gae/example-doodles-banner.png",
      description: "Entertainment-forward visual IP and product ecosystem.",
      chain: "ethereum",
      openseaUrl: "https://opensea.io/collection/doodles-official",
      officialWebsite: "https://doodles.app",
      xUrl: "https://x.com/doodles",
      discordUrl: "https://discord.gg/doodles",
      foundedAt: "2021-10-17T00:00:00.000Z",
      founderNames: ["Burnt Toast", "Poopie", "Tulip"],
      verified: true,
      claimed: false,
      hasToken: true,
      hasRewardPlatform: true,
      hasIrlEvents: true,
      hasBusinessRevenue: true,
      hasDevFounder: false,
      dataConfidenceLevel: "community_funded",
    },
    marketSnapshot: {
      collectionSlug: "doodles-official",
      floorPriceEth: 1.54,
      floorChange24hPct: 11.2,
      volume24hEth: 508,
      volume7dEth: 2024,
      sales24h: 143,
      holderCount: 5580,
      uniqueOwnerPct: 54.8,
      listedCount: 1190,
      listedPct: 11.9,
      topOfferEth: 1.38,
      bidDepthEth: 35.9,
      whaleConcentrationPct: 24.7,
      capturedAt: new Date().toISOString(),
    },
    score: {
      modelId: "nftscore_core",
      versionId: "version_v1_market_heavy",
      overallScore: 71,
      confidenceScore: 74,
      computedAt: new Date().toISOString(),
      categories: [],
      explainability: [],
    },
  },
];

export const MOCK_UPGRADE_CAMPAIGNS: ProjectUpgradeCampaign[] = [
  {
    id: "camp_azuki",
    collectionSlug: "azuki",
    targetUsd: 500,
    raisedUsd: 420,
    contributorCount: 33,
    status: "active",
    perks: [
      "Founder profile deep dive",
      "Community audit",
      "Early access full report",
      "Contributor badge",
    ],
  },
  {
    id: "camp_doodles",
    collectionSlug: "doodles-official",
    targetUsd: 500,
    raisedUsd: 500,
    contributorCount: 52,
    status: "funded",
    perks: [
      "Revenue model review",
      "IRL experience analysis",
      "Art/culture report",
      "Recognition on collection page",
    ],
  },
];

export const MOCK_PORTFOLIO: WalletPortfolioSummary = {
  walletAddress: "0x18E9134fA0d2F19Ba4e8fCAf6B3d7D3706AaC0B1",
  optimisticValueEth: 24.82,
  conservativeValueEth: 21.03,
  floorToOfferGapEth: 3.79,
  topMovers: ["doodles-official", "azuki"],
  risingFloors: ["doodles-official"],
  decliningFloors: ["pudgypenguins"],
  strongOffers: ["azuki"],
  potentialSellSignals: [
    "doodles-official: floor +11.2% in 24h with listing % rising",
    "pudgypenguins: score slipped 4 points this week",
  ],
  positions: [
    {
      collectionSlug: "azuki",
      collectionName: "Azuki",
      quantity: 2,
      floorValueEth: 11.84,
      bestOfferValueEth: 10.84,
      avgCostBasisEth: 8.5,
      unrealizedPnLEth: 3.34,
    },
    {
      collectionSlug: "pudgypenguins",
      collectionName: "Pudgy Penguins",
      quantity: 1,
      floorValueEth: 9.1,
      bestOfferValueEth: 8.7,
      avgCostBasisEth: 7.2,
      unrealizedPnLEth: 1.9,
    },
    {
      collectionSlug: "doodles-official",
      collectionName: "Doodles",
      quantity: 2,
      floorValueEth: 3.08,
      bestOfferValueEth: 2.76,
      avgCostBasisEth: 2.8,
      unrealizedPnLEth: 0.28,
    },
  ],
};

export const MOCK_WALLET_METRICS: WalletBehaviorMetrics = {
  walletAddress: MOCK_PORTFOLIO.walletAddress,
  walletAgeDays: 1210,
  avgHoldDays: 292,
  boughtCount: 142,
  soldCount: 96,
  mintCount: 21,
  saleFrequencyPerMonth: 1.8,
  realizedPnlEth: 12.6,
  unrealizedValueEth: MOCK_PORTFOLIO.optimisticValueEth,
  heldOver30Pct: 84,
  heldOver90Pct: 72,
  heldOver180Pct: 61,
  heldOver365Pct: 43,
  blueChipCount: 5,
  sellIntoPumpRate: 0.42,
  prePumpBuyRate: 0.58,
  tradingVolumeEth: 188,
  diversityScore: 0.74,
  ecosystemConcentrationPct: 0.68,
  collectionsFullyExited: 9,
  collectionsStillHeld: 14,
  communityParticipationScore: 0.79,
  collectionQualityScore: 0.83,
};
