export interface TopCollectionSeed {
  slug: string;
  name: string;
}

export const TOP_COLLECTION_SEEDS: TopCollectionSeed[] = [
  { slug: "cryptopunks", name: "CryptoPunks" },
  { slug: "boredapeyachtclub", name: "Bored Ape Yacht Club" },
  { slug: "mutant-ape-yacht-club", name: "Mutant Ape Yacht Club" },
  { slug: "azuki", name: "Azuki" },
  { slug: "pudgypenguins", name: "Pudgy Penguins" },
  { slug: "doodles-official", name: "Doodles" },
  { slug: "clone-x", name: "CloneX" },
  { slug: "moonbirds", name: "Moonbirds" },
  { slug: "otherdeed", name: "Otherdeed for Otherside" },
  { slug: "milady", name: "Milady Maker" },
  { slug: "lilpudgys", name: "Lil Pudgys" },
  { slug: "beanzofficial", name: "BEANZ Official" },
  { slug: "meebits", name: "Meebits" },
  { slug: "y00ts", name: "y00ts" },
  { slug: "degods-eth", name: "DeGods" },
  { slug: "rektguy", name: "Rektguy" },
  { slug: "kanpai-pandas", name: "Kanpai Pandas" },
  { slug: "llamaverse", name: "Llamaverse" },
  { slug: "sappy-seals", name: "Sappy Seals" },
  { slug: "cool-cats-nft", name: "Cool Cats" },
  { slug: "world-of-women-nft", name: "World of Women" },
  { slug: "mfers", name: "mfers" },
  { slug: "nouns", name: "Nouns" },
  { slug: "nounders", name: "Nounders" },
  { slug: "goblintownwtf", name: "goblintown.wtf" },
  { slug: "checks-vv", name: "Checks - VV" },
  { slug: "onchainmonkey", name: "OnChainMonkey" },
  { slug: "fidenza-by-tyler-hobbs", name: "Fidenza" },
  { slug: "chromie-squiggle-by-snowfro", name: "Chromie Squiggle" },
  { slug: "friendship-bracelets-by-alexis-anders", name: "Friendship Bracelets" },
  { slug: "the-captains", name: "The Captainz" },
  { slug: "memeland-potatoz", name: "Potatoz" },
  { slug: "karafuru", name: "Karafuru" },
  { slug: "digidaigaku", name: "DigiDaigaku" },
  { slug: "bored-ape-kennel-club", name: "Bored Ape Kennel Club" },
  { slug: "parallelalpha", name: "Parallel Alpha" },
  { slug: "vgxheroes", name: "VGX Heroes" },
  { slug: "the-weirdo-ghost-gang", name: "The Weirdo Ghost Gang" },
  { slug: "deadfellaz", name: "Deadfellaz" },
  { slug: "cyberkongz-vx", name: "CyberKongz VX" },
  { slug: "cyberkongz", name: "CyberKongz" },
  { slug: "moonbirds-oddities", name: "Moonbirds Oddities" },
  { slug: "supducks", name: "SupDucks" },
  { slug: "fatzuki", name: "Fatzuki" },
  { slug: "on-chain-gmon", name: "gmon" },
  { slug: "boredapechemclub", name: "Bored Ape Chemistry Club" },
  { slug: "v1-cryptopunks", name: "V1 CryptoPunks" },
  { slug: "0xmons", name: "0xmons" },
];
